{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "d7054f95-3d70-4a19-905c-2bf8e3632927",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import re\n",
    "import getpass\n",
    "import redis\n",
    "from typing import List, Dict\n",
    "from langchain.schema import Document\n",
    "from langchain.chat_models import ChatOpenAI\n",
    "from langchain.embeddings.openai import OpenAIEmbeddings\n",
    "from langchain.vectorstores import Redis\n",
    "from langchain.document_loaders import UnstructuredURLLoader\n",
    "from langchain.text_splitter import HTMLHeaderTextSplitter, RecursiveCharacterTextSplitter\n",
    "from langchain.chains import RetrievalQA\n",
    "from langchain.retrievers.self_query.base import SelfQueryRetriever\n",
    "from langchain.chains.query_constructor.base import (\n",
    "    get_query_constructor_prompt,\n",
    "    load_query_constructor_runnable,\n",
    "    AttributeInfo)\n",
    "import nltk\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.tokenize import word_tokenize\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "dddb2d8a-5915-4128-99ca-887b5975bbe5",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "OpenAI API Key: ········\n"
     ]
    }
   ],
   "source": [
    "os.environ[\"OPENAI_API_KEY\"] = getpass.getpass(\"OpenAI API Key:\")\n",
    "os.environ[\"LANGCHAIN_PROJECT\"] = \"html-chunking\"\n",
    "os.environ['TEXT_SOURCE'] = 'https://plato.stanford.edu/entries/goedel/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "6234ff54-4b5b-49a0-8ab6-787ab097195c",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package stopwords to\n",
      "[nltk_data]     C:\\Users\\JackMiller\\AppData\\Roaming\\nltk_data...\n",
      "[nltk_data]   Package stopwords is already up-to-date!\n",
      "[nltk_data] Downloading package punkt to\n",
      "[nltk_data]     C:\\Users\\JackMiller\\AppData\\Roaming\\nltk_data...\n",
      "[nltk_data]   Package punkt is already up-to-date!\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "nltk.download('stopwords')\n",
    "nltk.download('punkt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "21ac3421-614b-40ab-9a70-dea88399a4c8",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "def clean_text(content):\n",
    "    tokens = word_tokenize(content)\n",
    "    cleaned = ' '.join([t for t in tokens if t not in stopwords.words('english')])\n",
    "    return cleaned"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "6e0ee480-78f6-441c-ad77-a70448ea0b3c",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "llm = ChatOpenAI(model='gpt-3.5-turbo',\n",
    "                temperature=0)\n",
    "\n",
    "embeddings = OpenAIEmbeddings(show_progress_bar=True)\n",
    "\n",
    "loader = UnstructuredURLLoader([os.getenv('Text_SOURCE')])\n",
    "\n",
    "splitter = RecursiveCharacterTextSplitter(chunk_size=1000,\n",
    "                                         chunk_overlap=0)\n",
    "\n",
    "web_text = loader.load()\n",
    "web_text[0].page_content = clean_text(web_text[0].page_content)\n",
    "docs = splitter.split_documents(web_text)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d01aeb72-6b52-403e-8848-d7f2ca48e309",
   "metadata": {},
   "source": [
    "Create vectorstore and QA retriever"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "6e883694-2c0d-4d14-a41c-3b833adbf941",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.04s/it]\n"
     ]
    }
   ],
   "source": [
    "vector_store = Redis.from_documents(docs,\n",
    "                                   embeddings,\n",
    "                                   redis_url='redis://localhost:6379')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "id": "c0544a33-34fd-494f-988c-a0e351ddd1e5",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "retriever = RetrievalQA.from_chain_type(llm=llm,\n",
    "                                       chain_type='stuff',\n",
    "                                       retriever=vector_store.as_retriever(),\n",
    "                                       return_source_documents=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "id": "f153ed99-d098-42e5-9e54-67df0273e874",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "def print_result(response_obj):\n",
    "    print(\"SOURCES: \\n\")\n",
    "    cnt = 1\n",
    "    for source_doc in response_obj[\"source_documents\"]:\n",
    "        print(f\"Chunk #{cnt}\")\n",
    "        cnt += 1\n",
    "        print(\"Source Metadata: \", source_doc.metadata)\n",
    "        print(\"Source Text:\")\n",
    "        print(source_doc.page_content)\n",
    "        print(\"\\n\")\n",
    "    print(\"RESULT: \\n\")\n",
    "    print(response_obj[\"result\"] + \"\\n\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "id": "e2f54369-673d-41ab-aed4-3c2987da9d1e",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\307955947.py\", line 2, in <module>\n",
      "    response = retriever({\"query\":query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 139, in invoke\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\307955947.py\", line 2, in <module>\n",
      "    response = retriever({\"query\":query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 141, in _call\n",
      "    docs = self._get_docs(question, run_manager=_run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 221, in _get_docs\n",
      "    return self.retriever.get_relevant_documents(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\retrievers.py\", line 200, in get_relevant_documents\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.33it/s]\n",
      "score_threshold is deprecated. Use distance_threshold instead.score_threshold should only be used in similarity_search_with_relevance_scores.score_threshold will be removed in a future release.\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\307955947.py\", line 2, in <module>\n",
      "    response = retriever({\"query\":query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 144, in _call\n",
      "    answer = self.combine_documents_chain.run(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 543, in run\n",
      "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 139, in invoke\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\307955947.py\", line 2, in <module>\n",
      "    response = retriever({\"query\":query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 144, in _call\n",
      "    answer = self.combine_documents_chain.run(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 543, in run\n",
      "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\combine_documents\\base.py\", line 136, in _call\n",
      "    output, extra_return_dict = self.combine_docs(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\combine_documents\\stuff.py\", line 244, in combine_docs\n",
      "    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 293, in predict\n",
      "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 139, in invoke\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\307955947.py\", line 2, in <module>\n",
      "    response = retriever({\"query\":query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 144, in _call\n",
      "    answer = self.combine_documents_chain.run(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 543, in run\n",
      "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\combine_documents\\base.py\", line 136, in _call\n",
      "    output, extra_return_dict = self.combine_docs(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\combine_documents\\stuff.py\", line 244, in combine_docs\n",
      "    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 293, in predict\n",
      "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 103, in _call\n",
      "    response = self.generate([inputs], run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 115, in generate\n",
      "    return self.llm.generate_prompt(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\language_models\\chat_models.py\", line 544, in generate_prompt\n",
      "    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\language_models\\chat_models.py\", line 377, in generate\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "SOURCES: \n",
      "\n",
      "Chunk #1\n",
      "Source Metadata:  {'id': 'doc:5d1139e2b197483b9e83d64ed19f1cd1:d92e24c029384f8b96447dbfd07e65ed', 'source': 'https://plato.stanford.edu/entries/goedel/'}\n",
      "Source Text:\n",
      "completeness . As aside , von Neumann understood two theorems way , even Gödel . In fact von Neumann went much taking view showed infeasibility classical mathematics altogether . As wrote Carnap June 1931 : 9 ] And previous fall von Neumann written Gödel even stronger terms : It would take Gödel years see aspects Hilbert Program decisively refuted results ( Mancosu 2004 ) . 2.2.1 The First Incompleteness Theorem In Logical Journey ( Wang 1996 ) Hao Wang published full text material Gödel written ( Wang ’ request ) discovery incompleteness theorems . This material formed basis Wang ’ “ Some Facts Kurt Gödel , ” read approved Gödel : We see Gödel first tried reduce consistency problem analysis arithmetic . This seemed require truth definition arithmetic , turn led paradoxes , Liar paradox ( “ This sentence false ” ) Berry ’ paradox ( “ The least number defined expression consisting fourteen English words ” ) . Gödel noticed paradoxes would necessarily arise truth replaced provability .\n",
      "\n",
      "\n",
      "Chunk #2\n",
      "Source Metadata:  {'id': 'doc:5d1139e2b197483b9e83d64ed19f1cd1:8b4c39632e774dabafb7dbf7bdc5e5dd', 'source': 'https://plato.stanford.edu/entries/goedel/'}\n",
      "Source Text:\n",
      "Theorem extensively discussed van Atten Kennedy 2009 , well van Atten 2005 . 2.2 The Incompleteness Theorems Gödel mentioned possibility unsolvability question reals already 1929 thesis , arguing formalist principle Hilbert ’ , consistency criterion existence . In fact , giving finitary proof consistency analysis key desideratum known Hilbert program , along proving completeness . Accordingly Gödel ’ turn questions , especially first , led two incompleteness theorems . ( For discussion Hilbert Program reader referred standard references : Sieg 1990 , 1988 , 1999 ; Mancosu 1998 , Zach 2003 , Tait 1981 Tait 2002 . ) The First Incompleteness Theorem provides counterexample completeness exhibiting arithmetic statement neither provable refutable Peano arithmetic , though true standard model . The Second Incompleteness Theorem shows consistency arithmetic proved arithmetic . Thus Gödel ’ theorems demonstrated infeasibility Hilbert program , characterized particular desiderata , consistency\n",
      "\n",
      "\n",
      "Chunk #3\n",
      "Source Metadata:  {'id': 'doc:5d1139e2b197483b9e83d64ed19f1cd1:068bc9c0787649498b85a3ca83b8a9f5', 'source': 'https://plato.stanford.edu/entries/goedel/'}\n",
      "Source Text:\n",
      "First Incompleteness Theorem saw . This step omitted Gödel 1931 . He planned include step would second part II ( see footnote 48a Gödel 1931 ) . But instead writing turned continuum problem . [ 13 ] ( Part II elaborate points : ‘ true reason incompleteness , ’ applicability two theorems systems . ) He perhaps feel compelled attend looked like exercise formalization , relying instead informal argument convince ( succeeded ) . However step turned somewhat non-trivial . As Kleene puts introduction Gödel 1931 , informal presentation , “ Certainly idea argument Theorem XI ( consistency ) convincing ; turned execution details required somewhat work care anticipated. ” ( See pp . 126–141 Gödel 1986 . ) Eventually complete proof Second Theorem given Hilbert Bernays seventy pages Hilbert Bernays 1939 . A much compact treatment theorem given Löb Löb 1956 , subsequently Feferman , 1960 “ Arithmetization Metamathematics General Setting ” ( Feferman 1960/1961 ) , gave succinct completely general\n",
      "\n",
      "\n",
      "Chunk #4\n",
      "Source Metadata:  {'id': 'doc:5d1139e2b197483b9e83d64ed19f1cd1:dff3062e0f004341876b537b4a1f75af', 'source': 'https://plato.stanford.edu/entries/goedel/'}\n",
      "Source Text:\n",
      "But means arithmetic truth arithmetic provability co-extensive — whence First Incompleteness Theorem . This account Gödel ’ discovery told Hao Wang much fact ; Gödel ’ contemporary correspondence Bernays Zermelo , essentially description path theorems given . ( See Gödel 2003a Gödel 2003b respectively . ) From accounts see undefinability truth arithmetic , result credited Tarski , likely obtained form Gödel 1931 . But neither publicized published result ; biases logicians expressed time concerning notion truth , biases came vehemently fore Tarski announced results undefinability truth formal systems 1935 , may served deterrent Gödel ’ publication theorem . 2.2.2 The proof First Incompleteness Theorem We describe proof two theorems , formulating Gödel ’ results Peano arithmetic . Gödel used system related defined Principia Mathematica , containing Peano arithmetic . In presentation First Second Incompleteness Theorems refer Peano arithmetic P , following Gödel ’ notation . One main\n",
      "\n",
      "\n",
      "RESULT: \n",
      "\n",
      "Gödel's first incompleteness theorem states that in any consistent formal system that is capable of expressing basic arithmetic, there will always be true statements about numbers that cannot be proven within that system. In other words, there will always be mathematical statements that are true but cannot be derived or proven using the rules and axioms of the system.\n",
      "\n",
      "This theorem was a significant blow to Hilbert's program, which aimed to establish a complete and consistent foundation for all of mathematics. Gödel's theorem showed that no matter how rich or powerful a formal system is, it will always have inherent limitations and there will always be statements that are undecidable within that system.\n",
      "\n",
      "Gödel's proof for the first incompleteness theorem is complex and technical, but it involves constructing a statement that essentially says \"This statement cannot be proven within the system.\" By cleverly encoding this self-referential statement, Gödel was able to show that if the system is consistent, then this statement must be true but unprovable.\n",
      "\n",
      "This theorem has had profound implications for the philosophy of mathematics and the foundations of logic. It demonstrated that there are inherent limits to what can be achieved through formal systems and that there will always be mathematical truths that lie beyond our ability to prove them.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "query = \"explain godel's first incompleteness theorem.\"\n",
    "response = retriever({\"query\":query})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "id": "a3646384-d3a9-4f9c-aa5a-63721b2d82ba",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "SOURCES: \n",
      "\n",
      "Chunk #1\n",
      "Source Metadata:  {'id': 'doc:5d1139e2b197483b9e83d64ed19f1cd1:d92e24c029384f8b96447dbfd07e65ed', 'source': 'https://plato.stanford.edu/entries/goedel/'}\n",
      "Source Text:\n",
      "completeness . As aside , von Neumann understood two theorems way , even Gödel . In fact von Neumann went much taking view showed infeasibility classical mathematics altogether . As wrote Carnap June 1931 : 9 ] And previous fall von Neumann written Gödel even stronger terms : It would take Gödel years see aspects Hilbert Program decisively refuted results ( Mancosu 2004 ) . 2.2.1 The First Incompleteness Theorem In Logical Journey ( Wang 1996 ) Hao Wang published full text material Gödel written ( Wang ’ request ) discovery incompleteness theorems . This material formed basis Wang ’ “ Some Facts Kurt Gödel , ” read approved Gödel : We see Gödel first tried reduce consistency problem analysis arithmetic . This seemed require truth definition arithmetic , turn led paradoxes , Liar paradox ( “ This sentence false ” ) Berry ’ paradox ( “ The least number defined expression consisting fourteen English words ” ) . Gödel noticed paradoxes would necessarily arise truth replaced provability .\n",
      "\n",
      "\n",
      "Chunk #2\n",
      "Source Metadata:  {'id': 'doc:5d1139e2b197483b9e83d64ed19f1cd1:8b4c39632e774dabafb7dbf7bdc5e5dd', 'source': 'https://plato.stanford.edu/entries/goedel/'}\n",
      "Source Text:\n",
      "Theorem extensively discussed van Atten Kennedy 2009 , well van Atten 2005 . 2.2 The Incompleteness Theorems Gödel mentioned possibility unsolvability question reals already 1929 thesis , arguing formalist principle Hilbert ’ , consistency criterion existence . In fact , giving finitary proof consistency analysis key desideratum known Hilbert program , along proving completeness . Accordingly Gödel ’ turn questions , especially first , led two incompleteness theorems . ( For discussion Hilbert Program reader referred standard references : Sieg 1990 , 1988 , 1999 ; Mancosu 1998 , Zach 2003 , Tait 1981 Tait 2002 . ) The First Incompleteness Theorem provides counterexample completeness exhibiting arithmetic statement neither provable refutable Peano arithmetic , though true standard model . The Second Incompleteness Theorem shows consistency arithmetic proved arithmetic . Thus Gödel ’ theorems demonstrated infeasibility Hilbert program , characterized particular desiderata , consistency\n",
      "\n",
      "\n",
      "Chunk #3\n",
      "Source Metadata:  {'id': 'doc:5d1139e2b197483b9e83d64ed19f1cd1:068bc9c0787649498b85a3ca83b8a9f5', 'source': 'https://plato.stanford.edu/entries/goedel/'}\n",
      "Source Text:\n",
      "First Incompleteness Theorem saw . This step omitted Gödel 1931 . He planned include step would second part II ( see footnote 48a Gödel 1931 ) . But instead writing turned continuum problem . [ 13 ] ( Part II elaborate points : ‘ true reason incompleteness , ’ applicability two theorems systems . ) He perhaps feel compelled attend looked like exercise formalization , relying instead informal argument convince ( succeeded ) . However step turned somewhat non-trivial . As Kleene puts introduction Gödel 1931 , informal presentation , “ Certainly idea argument Theorem XI ( consistency ) convincing ; turned execution details required somewhat work care anticipated. ” ( See pp . 126–141 Gödel 1986 . ) Eventually complete proof Second Theorem given Hilbert Bernays seventy pages Hilbert Bernays 1939 . A much compact treatment theorem given Löb Löb 1956 , subsequently Feferman , 1960 “ Arithmetization Metamathematics General Setting ” ( Feferman 1960/1961 ) , gave succinct completely general\n",
      "\n",
      "\n",
      "Chunk #4\n",
      "Source Metadata:  {'id': 'doc:5d1139e2b197483b9e83d64ed19f1cd1:dff3062e0f004341876b537b4a1f75af', 'source': 'https://plato.stanford.edu/entries/goedel/'}\n",
      "Source Text:\n",
      "But means arithmetic truth arithmetic provability co-extensive — whence First Incompleteness Theorem . This account Gödel ’ discovery told Hao Wang much fact ; Gödel ’ contemporary correspondence Bernays Zermelo , essentially description path theorems given . ( See Gödel 2003a Gödel 2003b respectively . ) From accounts see undefinability truth arithmetic , result credited Tarski , likely obtained form Gödel 1931 . But neither publicized published result ; biases logicians expressed time concerning notion truth , biases came vehemently fore Tarski announced results undefinability truth formal systems 1935 , may served deterrent Gödel ’ publication theorem . 2.2.2 The proof First Incompleteness Theorem We describe proof two theorems , formulating Gödel ’ results Peano arithmetic . Gödel used system related defined Principia Mathematica , containing Peano arithmetic . In presentation First Second Incompleteness Theorems refer Peano arithmetic P , following Gödel ’ notation . One main\n",
      "\n",
      "\n",
      "RESULT: \n",
      "\n",
      "Gödel's first incompleteness theorem states that in any consistent formal system that is capable of expressing basic arithmetic, there will always be true statements about numbers that cannot be proven within that system. In other words, there will always be mathematical statements that are true but cannot be derived or proven using the rules and axioms of the system.\n",
      "\n",
      "This theorem was a significant blow to Hilbert's program, which aimed to establish a complete and consistent foundation for all of mathematics. Gödel's theorem showed that no matter how rich or powerful a formal system is, it will always have inherent limitations and there will always be statements that are undecidable within that system.\n",
      "\n",
      "Gödel's proof for the first incompleteness theorem is complex and technical, but it involves constructing a statement that essentially says \"This statement cannot be proven within the system.\" By cleverly encoding this self-referential statement, Gödel was able to show that if the system is consistent, then this statement must be true but unprovable.\n",
      "\n",
      "This theorem has had profound implications for the philosophy of mathematics and the foundations of logic. It demonstrated that there are inherent limits to what can be achieved through formal systems and that there will always be mathematical truths that lie beyond our ability to prove them.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print_result(response)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "id": "b9b5454d-398d-442f-80c0-3729e2a86fc3",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('page_content', 'Gödel’s proof of the consistency of the continuum hypothesis with the axioms of Zermelo-Fraenkel set theory is a tour de force and arguably the greatest achievement of his mathematical life. This is because aside from the arithmetization, virtually all of the technical machinery used in the proof had to be invented ab initio.  \\nThe Continuum Hypothesis (henceforth CH) was formulated by Georg Cantor, and was the first problem on Hilbert’s list of twenty-three unsolved problems as given in his famous address to the International Mathematical Congress in Paris in 1900. The problem as stated by Hilbert is as follows: Let A be an infinite set of real numbers. Then A is either countable, or has cardinality 2ℵ0, i.e., A is in one-to-one correspondence either with the set of natural numbers or with the set of all real numbers (otherwise known as the continuum). Another way to state the continuum hypothesis is that (the first uncountably infinite cardinal) ℵ1 = 2ℵ0.  \\nAs early as 1922 Skolem speculated that the CH was independent of the axioms for set theory given by Zermelo in 1908. Nevertheless Hilbert published a (false) proof of the CH in Hilbert 1926. In 1937 Gödel proved its consistency with the axioms of ZF set theory. (Henceforth we use the standard abbreviations for Zermelo-Fraenkel set theory, ZF, and Zermelo-Fraenkel set theory with the Axiom of Choice, ZFC.) The consistency of the negation of the CH was shown by Paul Cohen in 1961 (see Cohen 1963) and hence together with Gödel’s result one infers that the CH is independent of ZF (and ZFC).  \\nCohen invented an important new technique called forcing in the course of proving his result; this technique is at present the main method used to construct models of set theory. Forcing led to a revival of formalism among set theorists, the plurality of models being an indication of the “essential variability in set theory,” (Dehornoy 2004) and away from the notion that there is an intended model of set theory—a perspective Gödel advocated since at least 1947, if not earlier.[14] Recently there have been signs that the CH may again be coming to be regarded as a problem to be solved mathematically (with the help of course of some new evident axioms extending ZF). (See for example Woodin 2001a, 2002, 2001b, and Foreman 1998.) If any of the proposed solutions gain acceptance, this would confirm Gödel’s view that the CH would eventually be decided by finding an evident extension of the ZF axioms for set theory. The program associated with this view is called “Gödel’s Large Cardinal Program.”') \n",
      "\n",
      "('metadata', {'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.4 Gödel’s Work in Set theory', 'article_h4_subsection': '2.4.1 The consistency of the Continuum Hypothesis and the Axiom of Choice'}) \n",
      "\n",
      "('type', 'Document') \n",
      "\n"
     ]
    }
   ],
   "source": [
    "headers_to_split_on = [\n",
    "    (\"h1\", \"article_h1_main\"),\n",
    "    (\"h2\", \"article_h2_subsection\"),\n",
    "    (\"h3\", \"article_h3_subsection\"),\n",
    "    (\"h4\", \"article_h4_subsection\"),\n",
    "]\n",
    "\n",
    "html_splitter = HTMLHeaderTextSplitter(\n",
    "    headers_to_split_on=headers_to_split_on,\n",
    "    return_each_element=False)\n",
    "\n",
    "docs = html_splitter.split_text_from_url('https://plato.stanford.edu/entries/goedel/' )\n",
    "\n",
    "for attr in docs[12]:\n",
    "    print(attr, \"\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "id": "65a4e5b1-2115-4657-815e-1daa9c86cd8a",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'article_h1_main': 'Kurt Gödel'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '1. Biographical Sketch'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.1 The Completeness Theorem', 'article_h4_subsection': '2.1.1 Introduction'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.1 The Completeness Theorem', 'article_h4_subsection': '2.1.2 Proof of the Completeness Theorem'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.1 The Completeness Theorem', 'article_h4_subsection': '2.1.3 An Important Consequence of the Completeness Theorem'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.2 The Incompleteness Theorems'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.2 The Incompleteness Theorems', 'article_h4_subsection': '2.2.1 The First Incompleteness Theorem'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.2 The Incompleteness Theorems', 'article_h4_subsection': '2.2.2 The proof of the First Incompleteness Theorem'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.2 The Incompleteness Theorems', 'article_h4_subsection': '2.2.3 The Second Incompleteness Theorem'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.3 Speed-up Theorems'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.4 Gödel’s Work in Set theory', 'article_h4_subsection': '2.4.1 The consistency of the Continuum Hypothesis and the Axiom of Choice'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.4 Gödel’s Work in Set theory', 'article_h4_subsection': '2.4.2 Gödel’s Proof of the Consistency of the Continuum Hypothesis and the Axiom of Choice with the Axioms of Zermelo-Fraenkel Set Theory'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.4 Gödel’s Work in Set theory', 'article_h4_subsection': '2.4.3 Consequences of Consistency'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.4 Gödel’s Work in Set theory', 'article_h4_subsection': '2.4.4 Gödel’s view of the Axiom of Constructibility'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.5 Gödel’s Work in Intuitionistic Logic and Arithmetic'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.5 Gödel’s Work in Intuitionistic Logic and Arithmetic', 'article_h4_subsection': '2.5.1 Intuitionistic Propositional Logic is not Finitely-Valued'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.5 Gödel’s Work in Intuitionistic Logic and Arithmetic', 'article_h4_subsection': '2.5.2 Classical Arithmetic is Interpretable in Heyting Arithmetic'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.5 Gödel’s Work in Intuitionistic Logic and Arithmetic', 'article_h4_subsection': '2.5.3 Intuitionistic Propositional Logic is Interpretable in S4'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.5 Gödel’s Work in Intuitionistic Logic and Arithmetic', 'article_h4_subsection': '2.5.4 Heyting Arithmetic is Interpretable into Computable Functionals of Finite Type.'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '3. Gödel’s Philosophical Views'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '3. Gödel’s Philosophical Views', 'article_h3_subsection': '3.1 Gödel’s Rationalism'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '3. Gödel’s Philosophical Views', 'article_h3_subsection': '3.2 Gödel’s Realism'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': 'Bibliography', 'article_h3_subsection': 'Primary Sources', 'article_h4_subsection': 'Gödel’s Writings'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': 'Bibliography', 'article_h3_subsection': 'Primary Sources', 'article_h4_subsection': 'The Collected Papers of Kurt Gödel'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': 'Bibliography', 'article_h3_subsection': 'Secondary Sources'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': 'Academic Tools'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': 'Other Internet Resources'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': 'Related Entries'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel'} \n",
      "\n",
      "{'article_h1_main': 'Kurt Gödel', 'article_h3_subsection': 'Acknowledgments'} \n",
      "\n",
      "{'article_h4_subsection': 'Browse'} \n",
      "\n",
      "{'article_h4_subsection': 'About'} \n",
      "\n",
      "{'article_h4_subsection': 'Support SEP'} \n",
      "\n",
      "{'article_h4_subsection': 'Mirror Sites'} \n",
      "\n"
     ]
    }
   ],
   "source": [
    "for doc in docs:\n",
    "    if doc.metadata:\n",
    "        print(doc.metadata, \"\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "id": "f811c882-89fd-4f63-8aa3-da977c70aba2",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'text': [{'name': 'article_h1_main'}, {'name': 'article_h2_subsection'}, {'name': 'article_h3_subsection'}, {'name': 'article_h4_subsection'}]}\n"
     ]
    }
   ],
   "source": [
    "def build_index_schema(documents: List[Document]) -> Dict:\n",
    "    schema = {\"text\": []}\n",
    "    for doc in documents:\n",
    "        for key in doc.metadata:\n",
    "            name_dict = {\"name\": f\"{key}\"}\n",
    "            if name_dict not in schema[\"text\"]:\n",
    "                schema[\"text\"].append(name_dict)\n",
    "    return schema\n",
    "\n",
    "index_schema = build_index_schema(docs)\n",
    "print(index_schema)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "id": "e78bf045-bbeb-4e54-9044-0f87424d6a4e",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "`index_schema` does not match generated metadata schema.\n",
      "If you meant to manually override the schema, please ignore this message.\n",
      "index_schema: {'text': [{'name': 'article_h1_main'}, {'name': 'article_h2_subsection'}, {'name': 'article_h3_subsection'}, {'name': 'article_h4_subsection'}]}\n",
      "generated_schema: {'text': [], 'numeric': [], 'tag': []}\n",
      "\n",
      "100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.13s/it]\n"
     ]
    }
   ],
   "source": [
    "vectorstore = Redis.from_documents(\n",
    "    docs,\n",
    "    embeddings,\n",
    "    redis_url='redis://localhost:6379',\n",
    "    index_schema = index_schema\n",
    ")\n",
    "retriever = RetrievalQA.from_chain_type(\n",
    "    llm=llm,\n",
    "    chain_type=\"stuff\",\n",
    "    retriever=vectorstore.as_retriever(),\n",
    "    return_source_documents=True\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 108,
   "id": "b91c1154-1426-4c1a-a94d-74f05366b5a5",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\1885318157.py\", line 2, in <module>\n",
      "    response = retriever({\"query\": query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 139, in invoke\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\1885318157.py\", line 2, in <module>\n",
      "    response = retriever({\"query\": query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 141, in _call\n",
      "    docs = self._get_docs(question, run_manager=_run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 221, in _get_docs\n",
      "    return self.retriever.get_relevant_documents(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\retrievers.py\", line 200, in get_relevant_documents\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.39it/s]\n",
      "score_threshold is deprecated. Use distance_threshold instead.score_threshold should only be used in similarity_search_with_relevance_scores.score_threshold will be removed in a future release.\n",
      "Metadata key article_h3_subsection not found in metadata. Setting to None. \n",
      "Metadata fields defined for this instance: ['article_h1_main', 'article_h2_subsection', 'article_h3_subsection', 'article_h4_subsection']\n",
      "Metadata key article_h4_subsection not found in metadata. Setting to None. \n",
      "Metadata fields defined for this instance: ['article_h1_main', 'article_h2_subsection', 'article_h3_subsection', 'article_h4_subsection']\n",
      "Metadata key article_h4_subsection not found in metadata. Setting to None. \n",
      "Metadata fields defined for this instance: ['article_h1_main', 'article_h2_subsection', 'article_h3_subsection', 'article_h4_subsection']\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\1885318157.py\", line 2, in <module>\n",
      "    response = retriever({\"query\": query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 144, in _call\n",
      "    answer = self.combine_documents_chain.run(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 543, in run\n",
      "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 139, in invoke\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\1885318157.py\", line 2, in <module>\n",
      "    response = retriever({\"query\": query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 144, in _call\n",
      "    answer = self.combine_documents_chain.run(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 543, in run\n",
      "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\combine_documents\\base.py\", line 136, in _call\n",
      "    output, extra_return_dict = self.combine_docs(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\combine_documents\\stuff.py\", line 244, in combine_docs\n",
      "    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 293, in predict\n",
      "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 139, in invoke\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1944, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 96, in __init__\n",
      "    self.client = client or get_client()\n",
      "                            ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\tracers\\langchain.py\", line 56, in get_client\n",
      "    _CLIENT = Client()\n",
      "              ^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 378, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langsmith\\client.py\", line 245, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 703, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\logging\\__init__.py\", line 392, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JackMiller\\AppData\\Local\\Temp\\ipykernel_22372\\1885318157.py\", line 2, in <module>\n",
      "    response = retriever({\"query\": query})\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\retrieval_qa\\base.py\", line 144, in _call\n",
      "    answer = self.combine_documents_chain.run(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 543, in run\n",
      "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\combine_documents\\base.py\", line 136, in _call\n",
      "    output, extra_return_dict = self.combine_docs(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\combine_documents\\stuff.py\", line 244, in combine_docs\n",
      "    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 293, in predict\n",
      "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\_api\\deprecation.py\", line 145, in warning_emitting_wrapper\n",
      "    return wrapped(*args, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 363, in __call__\n",
      "    return self.invoke(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 103, in _call\n",
      "    response = self.generate([inputs], run_manager=run_manager)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain\\chains\\llm.py\", line 115, in generate\n",
      "    return self.llm.generate_prompt(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\language_models\\chat_models.py\", line 544, in generate_prompt\n",
      "    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\language_models\\chat_models.py\", line 377, in generate\n",
      "    callback_manager = CallbackManager.configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1400, in configure\n",
      "    return _configure(\n",
      "  File \"C:\\Users\\JackMiller\\anaconda3\\envs\\LLM\\Lib\\site-packages\\langchain_core\\callbacks\\manager.py\", line 1947, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n"
     ]
    }
   ],
   "source": [
    "query = \"explain godel's first incompleteness theorem.\"\n",
    "response = retriever({\"query\": query})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "id": "2c5c9b41-3bab-4c71-ab61-6a0d4d081e33",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "SOURCES: \n",
      "\n",
      "Chunk #1\n",
      "Source Metadata:  {'id': 'doc:009238b9df654e079fa106ac9bd23353:39da3bf11eed4a109c9efe17bcd0031e', 'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.2 The Incompleteness Theorems', 'article_h4_subsection': '2.2.3 The Second Incompleteness Theorem'}\n",
      "Source Text:\n",
      "The Second Incompleteness Theorem establishes the unprovability, in number theory, of the consistency of number theory. First we have to write down a number-theoretic formula that expresses the consistency of the axioms. This is surprisingly simple. We just let Con(P) be the sentence ¬Prov(⌈0 = 1⌉).  \n",
      "Theorem 4 (Gödel’s Second Incompleteness Theorem) If P is consistent, then Con(P) is not provable from P.  \n",
      "Proof: Let φ be as in (3). The reasoning used to infer ‘if P ⊢ φ, then P ⊢ 0 ≠ 1‘ does not go beyond elementary number theory, and can therefore, albeit with a lot of effort (see below), be formalized in P. This yields: P ⊢ (Prov(⌈φ⌉) → ¬Con(P)), and thus by (3), P ⊢ (Con(P) → φ). Since P ⊬ φ, we must have P ⊬ Con(P).  \n",
      "The above proof (sketch) of the Second Incompleteness Theorem is deceptively simple as it avoids the formalization. A rigorous proof would have to establish the proof of ‘if P ⊢ φ, then P ⊢ 0 ≠ 1’ in P.  \n",
      "It is noteworthy that ω-consistency is not needed in the proof of Gödel’s Second Incompleteness Theorem. Also note that neither is ¬Con(P) provable, by the consistency of P and the fact, now known as Löb’s theorem, that P ⊢ Prov(⌈φ⌉) implies P ⊢ φ.  \n",
      "The assumption of ω-consistency in the First Incompleteness Theorem was eliminated by Rosser in 1936, and replaced by the weaker notion of consistency. Rosser’s generalization involves applying the fixed point theorem to the formula R(x): ‘for all z: either z is not the Gödel number of a proof of the formula with Gödel number x or there is a proof shorter than z of the negation of (the formula with Gödel number) x’ (see Rosser 1936).  \n",
      "With regard to the Second Incompleteness Theorem, the argument relies in part on formalizing the proof of the First Incompleteness Theorem as we saw. This step is omitted in Gödel 1931. He planned to include the step in what would have been a second part II (see footnote 48a of Gödel 1931). But instead of writing it he turned to the continuum problem.[13] (Part II was to elaborate on other points too: the ‘true reason for incompleteness,’ and the applicability of the two theorems to other systems.) He perhaps did not feel compelled to attend to what looked like an exercise in formalization, relying instead on the informal argument to convince (in which it succeeded). However this step turned out to be somewhat non-trivial. As Kleene puts it in his introduction to Gödel 1931, of the informal presentation, “Certainly the idea of the argument for Theorem XI (consistency) was very convincing; but it turned out that the execution of the details required somewhat more work and care than had been anticipated.” (See pp. 126–141 of Gödel 1986.) Eventually a complete proof of the Second Theorem was given by Hilbert and Bernays in some seventy pages in their Hilbert and Bernays 1939. A much more compact treatment of the theorem was given by Löb in his Löb 1956, and subsequently Feferman, in his 1960 “Arithmetization of Metamathematics in a General Setting” (Feferman 1960/1961), gave a succinct and completely general treatment of both the First and Second Theorems. But see the supplementary document:  \n",
      "Did the Incompleteness Theorems Refute Hilbert’s Program?  \n",
      "For more detailed discussion, see the entry on Gödel’s incompleteness theorems.\n",
      "\n",
      "\n",
      "Chunk #2\n",
      "Source Metadata:  {'id': 'doc:009238b9df654e079fa106ac9bd23353:d4c2bdb9cd4b437bace3a6c555633352', 'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': 'Related Entries', 'article_h3_subsection': None, 'article_h4_subsection': None}\n",
      "Source Text:\n",
      "Gödel, Kurt: incompleteness theorems | Hilbert, David: program in the foundations of mathematics | Husserl, Edmund | Leibniz, Gottfried Wilhelm | mathematics, philosophy of: intuitionism | mathematics, philosophy of: Platonism | model theory | model theory: first-order | phenomenology | realism | set theory | set theory: continuum hypothesis | set theory: large cardinals and determinacy\n",
      "\n",
      "\n",
      "Chunk #3\n",
      "Source Metadata:  {'id': 'doc:009238b9df654e079fa106ac9bd23353:e1b8463b3a0f40c09adc7b98d9832337', 'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.2 The Incompleteness Theorems', 'article_h4_subsection': '2.2.2 The proof of the First Incompleteness Theorem'}\n",
      "Source Text:\n",
      "We now describe the proof of the two theorems, formulating Gödel’s results in Peano arithmetic. Gödel himself used a system related to that defined in Principia Mathematica, but containing Peano arithmetic. In our presentation of the First and Second Incompleteness Theorems we refer to Peano arithmetic as P, following Gödel’s notation.  \n",
      "Before proceeding to the details of the formal proof, we define the notion of ω-consistency used by Gödel in the First Incompleteness Theorem: P is ω-consistent if P ⊢ ¬φ(n) for all n implies P ⊬ ∃xφ(x). Naturally this implies consistency and follows from the assumption that the natural numbers satisfy the axioms of Peano arithmetic.  \n",
      "One of the main technical tools used in the proof is Gödel numbering, a mechanism which assigns natural numbers to terms and formulas of our formal theory P. There are different ways of doing this. The most common is based on the unique representation of natural numbers as products of powers of primes. Each symbol s of number theory is assigned a positive natural number #(s) in a fixed but arbitrary way, e.g.  \n",
      "#(0) = 1 #(=) = 5 #(¬) = 9 #(1) = 2 #( ( ) = 6 #(∀) = 10 #(+) = 3 #( ) ) = 7 #(vi) = 11 + i #(×) = 4 #(∧) = 8    \n",
      "The natural number corresponding to a sequence w = < w0,…, wk > of symbols is  \n",
      "⌈w⌉ = 2#(w0) · 3#(w1) · … · pk#(wk),  \n",
      "where pk is the k+1st prime. It is called its Gödel number and denoted by ⌈w⌉. In this way we can assign Gödel numbers to formulas, sequences of formulas (once a method for distinguishing when one formula ends and another begins has been adopted), and most notably, proofs.  \n",
      "An essential point here is that when a formula is construed as a natural number, then the numeral corresponding to that natural number can occur as the argument of a formula, thus enabling the syntax to “refer” to itself, so to speak (i.e., when a numeral is substituted into a formula the Gödel number of which the numeral represents). This will eventually allow Gödel to formalize the Liar paradox (with “provability” in place of “truth”) by substituting into the formula which says, ‘the formula, whose code is x, is unprovable,’ its own natural number code (or more precisely the corresponding numeral).  \n",
      "Another concept required to carry out the formalization is the concept of numeralwise expressibility of number theoretic predicates. A number-theoretic formula φ(n1, …, nk) is numeralwise expressible in P if for each tuple of natural numbers (n1, …, nk):  \n",
      "N ⊨ φ(n1, …, nk) ⇒ P ⊢ φ(n1, …, nk) N ⊨ ¬φ(n1, …, nk) ⇒ P ⊢ ¬φ(n1, …, nk)  \n",
      "where n is the formal term which denotes the natural number n. (In P, this is S(S(…S(0)…), where n is the number of iterations of the successor function applied to the constant symbol 0.) One of the principal goals is to numeralwise express the predicate  \n",
      "Prf(x, y): ‘the sequence with Gödel number x is a proof of the sentence with Gödel number y.’  \n",
      "Reaching this goal involves defining forty-five relations, each defined in terms of the preceding ones. These relations are all primitive recursive.[10] Relations needed are, among others, those which assert of a natural number that it codes a sequence, or a formula, or an axiom, or that it is the code, denoted by Sb(ru1…unZ(x1)…Z(xn)), of a formula obtained from a formula with code r by substituting for its free variable ui the xi th numeral for i = 1, …, n. The forty-fifth primitive recursive relation defined is Prf(x, y), and the forty-sixth is  \n",
      "Prov(y): ‘the sentence with Gödel number y is provable in P’  \n",
      "which without being primitive recursive, is however obtained from Prf(x, y) by existentially quantifying x. (Prov(y) satisfies only the ‘positive’ part of numeralwise expressibility, and not the negative part; but the negative part is not needed.)  \n",
      "In Theorem V of his paper, Gödel proves that any number theoretic predicate which is primitive recursive is numeralwise expressible in P. Thus since Prf(x, y) and substitution are primitive recursive, these are decided by P when closed terms are substituted for the free variables x and y. This is the heart of the matter as we will see. Another key point about numeralwise expressibility is that although we informally interpret, for example, Prov(Sb(ru1…unZ(x1)…Z(xn))), by: ‘the formula with Gödel number r is provable if the Gödel number for the xi th numeral is substituted in place of the i th variable,’ neither the formal statement within the theory P nor anything we prove about it appeals to such meanings. On the contrary Prov(Sb(ru1…unZ(x1)…Z(xn))), is a meaningless string of logical and arithmetical symbols. As Gödel puts it in his introduction to his theorem V, ‘The fact that can be formulated vaguely by saying that every recursive relation is definable in the system P (if the usual meaning is given to the formulas of this system) is expressed in precise language, without reference to any interpretation of the formulas of P, by the following Theorem (V) (Gödel 1986, p. 171, italics Gödel’s).  \n",
      "Gödel in his incompleteness theorems uses a method given in what is called nowadays Gödel’s Fixed Point Theorem. Although Gödel constructs a fixed point in the course of proving the incompleteness theorem, he does not state the fixed point theorem explicitly. The fixed point theorem is as follows:  \n",
      "Theorem 2 (Gödel’s Fixed Point Theorem) If φ(v0) is a formula of number theory, then there is a sentence ψ such that P ⊢ ψ ↔ φ(⌈ψ⌉), where ⌈ψ⌉ is the formal term corresponding to the natural number code of ⌈ψ⌉.  \n",
      "Proof: Let σ(x,y,z) be a formula that numeralwise expresses the number theoretic predicate ‘y is the Gödel number of the formula obtained by replacing the variable v0 in the formula whose Gödel number is x by the term z’. Let θ(v0) be the formula ∃v1(φ(v1) ∧ σ(v0, v1, v0)). Let k = ⌈θ(v0)⌉ and ψ = θ(k). Now directly by the construction P ⊢ ψ ↔ φ(⌈ψ⌉).  \n",
      "A sentence is refutable from a theory if its negation is provable. The First Incompleteness Theorem as Gödel stated it is as follows:  \n",
      "Theorem 3 (Gödel’s First Incompleteness Theorem) If P is ω-consistent, then there is a sentence which is neither provable nor refutable from P.  \n",
      "Proof: By judicious coding of syntax referred to above, write a formula Prf(x,y)[11] of number theory, representable in P, so that  \n",
      "n codes a proof of φ ⇒ P ⊢ Prf(n, ⌈φ⌉).  \n",
      "and  \n",
      "n does not code a proof of φ ⇒ P ⊢ ¬Prf(n, ⌈φ⌉).  \n",
      "Let Prov(y) denote the formula ∃x Prf(x,y)[12]. By Theorem 2 there is a sentence φ with the property  \n",
      "P ⊢ (φ ↔ ¬Prov(⌈φ⌉)).  \n",
      "Thus φ says ‘I am not provable.’ We now observe, if P ⊢ φ, then by (1) there is n such that P ⊢ Prf(n, ⌈φ⌉), hence P ⊢ Prov(⌈φ⌉), hence, by (3) P ⊢ ¬φ, so P is inconsistent. Thus  \n",
      "P ⊬ φ  \n",
      "Furthermore, by (4) and (2), we have P ⊢ ¬Prf(n, ⌈φ⌉) for all natural numbers n. By ω-consistency P ⊬ ∃x Prf(x, ⌈φ⌉). Thus (3) gives P ⊬ ¬φ. We have shown that if P is ω-consistent, then φ is independent of P.  \n",
      "On concluding the proof of the first theorem, Gödel remarks, “we can readily see that the proof just given is constructive; that is … proved in an intuitionistically unobjectionable manner…” (Gödel 1986, p. 177). This is because, as he points out, all the existential statements are based on his theorem V (giving the numeralwise expressibility of primitive recursive relations), which is intuitionistically unobjectionable.\n",
      "\n",
      "\n",
      "Chunk #4\n",
      "Source Metadata:  {'id': 'doc:009238b9df654e079fa106ac9bd23353:993324427d244585bb721786537313a6', 'article_h1_main': 'Kurt Gödel', 'article_h2_subsection': '2. Gödel’s Mathematical Work', 'article_h3_subsection': '2.2 The Incompleteness Theorems', 'article_h4_subsection': None}\n",
      "Source Text:\n",
      "Gödel mentioned the possibility of the unsolvability of a question about the reals already in his 1929 thesis, in arguing against the formalist principle of Hilbert’s, that consistency is a criterion for existence. In fact, giving a finitary proof of the consistency of analysis was a key desideratum of what was then known as the Hilbert program, along with proving its completeness. Accordingly it was Gödel’s turn to these questions, especially the first, which led him to the two incompleteness theorems. (For a discussion of the Hilbert Program the reader is referred to the standard references: Sieg 1990, 1988, 1999; Mancosu 1998, Zach 2003, Tait 1981 and Tait 2002.)  \n",
      "The First Incompleteness Theorem provides a counterexample to completeness by exhibiting an arithmetic statement which is neither provable nor refutable in Peano arithmetic, though true in the standard model. The Second Incompleteness Theorem shows that the consistency of arithmetic cannot be proved in arithmetic itself. Thus Gödel’s theorems demonstrated the infeasibility of the Hilbert program, if it is to be characterized by those particular desiderata, consistency and completeness.  \n",
      "As an aside, von Neumann understood the two theorems this way, even before Gödel did. In fact von Neumann went much further in taking the view that they showed the infeasibility of classical mathematics altogether. As he wrote to Carnap in June of 1931:  \n",
      "Thus today I am of the opinion that 1. Gödel has shown the unrealizability of Hilbert’s program. 2. There is no more reason to reject intuitionism (if one disregards the aesthetic issue, which in practice will also for me be the decisive factor). Therefore I consider the state of the foundational discussion in Königsberg to be outdated, for Gödel’s fundamental discoveries have brought the question to a completely different level.[9]  \n",
      "And the previous fall von Neumann had written to Gödel in even stronger terms:  \n",
      "Thus, I think that your result has solved negatively the foundational question: there is no rigorous justification for classical mathematics. (Gödel 2003b, p. 339)  \n",
      "It would take Gödel himself a few years to see that those aspects of the Hilbert Program had been decisively refuted by his results (Mancosu 2004).\n",
      "\n",
      "\n",
      "RESULT: \n",
      "\n",
      "Gödel's First Incompleteness Theorem states that in any consistent formal system that is capable of expressing basic arithmetic, there exists a statement that is true but cannot be proven within the system itself. In other words, there are mathematical truths that cannot be derived from the axioms and rules of the system.\n",
      "\n",
      "To understand this theorem, we need to consider Gödel's method of encoding statements and proofs as numbers. He assigned a unique number, called a Gödel number, to each symbol, formula, and proof in the system. This allowed him to treat mathematical statements and proofs as mathematical objects that could be manipulated within the system.\n",
      "\n",
      "Gödel then constructed a formula, called Prf(x, y), which represents the statement \"x is the Gödel number of a proof of the formula with Gödel number y.\" This formula is representable within the system itself. Using this formula, Gödel showed that there is a sentence, let's call it φ, that says \"I am not provable.\"\n",
      "\n",
      "Now, if the system is consistent, it cannot prove φ because if it could, it would contradict its own consistency. On the other hand, if the system could prove ¬φ (the negation of φ), it would also contradict its own consistency because it would mean that the system can prove a false statement. Therefore, φ is a true statement that cannot be proven or refuted within the system.\n",
      "\n",
      "This result has profound implications for the foundations of mathematics. It shows that no formal system can be both complete (able to prove all true statements) and consistent (not able to prove any false statements). It also challenges the idea that the truth of mathematical statements can be determined solely by the rules and axioms of a formal system.\n",
      "\n",
      "Gödel's First Incompleteness Theorem has had a significant impact on the philosophy of mathematics and the study of formal systems. It demonstrated the limitations of formal systems and raised questions about the nature of mathematical truth and the foundations of mathematics.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print_result(response)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "66b73c70-0e56-413d-b84a-e6bc6e5d5fec",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "LLM",
   "language": "python",
   "name": "llm"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
